### ISSUE TITLE
local_part-suffix in spam-router?

### ISSUE THREAD

**Issue by Udera** [vexim/vexim2#137]
Do we want spam-mails to a local_part_suffix to be filtered as well? Especially these routers:
https://github.com/vexim/vexim2/blob/master/docs/configure#L514-L551

**Comment by rimas-kudelis** [comment]
Wow, that's a good question.
On one hand, we probably don't want to validate more addresses than necessary for spammers and/or malware senders, on the other hand, if these addresses accept normal e-mails, then perhaps they should reject potentially malicious e-mails as if they exist as well, just to make debugging easier.
Just think about it: you send an e-mail to your friend john+foo@example.org, and it's delivered. Then you send another e-mail, which is treated as spam, but what you get is not a "rejected because spam", reply but a "rejected because recipient doesn't exist" one instead. That would be quite confusing, don't you think?

**Comment by Udera** [comment]
Why would we validate more addresses? If you use the local_part_suffix, the `virtual_domains`-router will always accept the mail.

We don't reject mail because of spam (except you enable this https://github.com/vexim/vexim2/blob/master/docs/vexim-acl-check-content.conf#L31-L35) and if it is spam, we would put it in john's spam-folder (except of delivering it into his mailbox).

**Comment by rimas-kudelis** [comment]
Well in that case I'm not sure I understand your initial question.

**Comment by Udera** [comment]
Just that we add
````
  .ifdef VEXIM_LOCALPART_SUFFIX
    local_part_suffix = VEXIM_LOCALPART_SUFFIX
    local_part_suffix_optional
  .endif
````
to the `ditch_spam`-router. Probably not the `ditch_spam_drop` as it is only used for mail forwards to external addresses.
