### ISSUE TITLE
Can't add relay domains

### ISSUE THREAD

**Issue by Udera** [vexim/vexim2#87]
As siteadmin, you can't add relay-domains. The function is implemented in the routers...

**Comment by rimas-kudelis** [comment]
Sorry, your problem description and the commit just don't add up. Please explain in more detail.

**Comment by Udera** [comment]
If you add a relay domain, the `maildir`-field in the `domains`-table is empty. But it must not be `NULL`:
https://github.com/vexim/vexim2/blob/master/setup/mysql.sql#L16
So, I modified the sql-query to set `/dev/null` as maildir.

**Comment by rimas-kudelis** [comment]
`maildir` defaults to an empty string. I think this is what you should be using instead of /dev/null, no?

**Comment by Udera** [comment]
Is there a difference between an empty string and `NULL`?

**Comment by rimas-kudelis** [comment]
well, the line you are quoting says:
```mysql
maildir varchar(128) NOT NULL default '',
```
So this field will accept `''`, but will not accept `NULL`. If the problem you are fixing is that you can't add a relay domain due to failing `INSERT` statement, then I guess the right way to fix it is to pass empty `maildir`. Specifying `/dev/null` is not necessary in that case.

On the other hand, if you are fixing a different problem (e.g. that relay domains can be added but don't work properly), you should really describe it better. :)

**Comment by Udera** [comment]
What I don't understand, when the `INSERT`-query doesn't specify a value for `maildir` why doesn't MySQL set it to the default `''`? Therefore I supposed that `''` is not permitted or set to `NULL`.
I will try to use an empty string.

**Comment by rimas-kudelis** [comment]
I think I had a similar issue at work just a few months ago.
The thing is, if you omit `maildir` altogether, it will be set to the default value. But passing a `NULL` is not the same as omitting, hence the error.

**Comment by Udera** [comment]
Ok, I updated the pull request and the empty string `''` does work.
